# Generated by Django 4.0.4 on 2022-12-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
    ]
