# Generated by Django 4.0.4 on 2022-12-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_health_news_science_news_sport_news_tech_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_news',
            name='content',
            field=models.TextField(max_length=250),
        ),
    ]
