# Generated by Django 4.0.4 on 2022-12-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_business_news_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_news',
            name='img',
            field=models.ImageField(default='business_images/default.jpg', upload_to='business_images/'),
        ),
        migrations.AddField(
            model_name='health_news',
            name='img',
            field=models.ImageField(default='business_images/default.jpg', upload_to='business_images/'),
        ),
        migrations.AddField(
            model_name='science_news',
            name='img',
            field=models.ImageField(default='business_images/default.jpg', upload_to='business_images/'),
        ),
        migrations.AddField(
            model_name='sport_news',
            name='img',
            field=models.ImageField(default='business_images/default.jpg', upload_to='business_images/'),
        ),
        migrations.AddField(
            model_name='tech_news',
            name='img',
            field=models.ImageField(default='business_images/default.jpg', upload_to='business_images/'),
        ),
    ]
