# Generated by Django 4.0.4 on 2023-01-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_business_news_img_alter_health_news_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_news',
            name='custom_filename',
            field=models.CharField(default='default', max_length=250),
        ),
        migrations.AddField(
            model_name='science_news',
            name='custom_filename',
            field=models.CharField(default='default', max_length=250),
        ),
        migrations.AddField(
            model_name='sport_news',
            name='custom_filename',
            field=models.CharField(default='default', max_length=250),
        ),
        migrations.AddField(
            model_name='tech_news',
            name='custom_filename',
            field=models.CharField(default='default', max_length=250),
        ),
    ]
