# Generated by Django 4.0.4 on 2023-01-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_health_news_custom_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_news',
            name='img',
            field=models.ImageField(default='static/health_images/default.jpg', upload_to='health_images/'),
        ),
        migrations.AlterField(
            model_name='science_news',
            name='img',
            field=models.ImageField(default='static/science_images/default.jpg', upload_to='science_images/'),
        ),
        migrations.AlterField(
            model_name='sport_news',
            name='img',
            field=models.ImageField(default='static/sport_images/default.jpg', upload_to='sport_images/'),
        ),
        migrations.AlterField(
            model_name='tech_news',
            name='img',
            field=models.ImageField(default='static/tech_images/default.jpg', upload_to='tech_images/'),
        ),
    ]
