# Generated by Django 4.0.4 on 2023-01-02 09:55

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_health_news_img_alter_science_news_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_news',
            name='img',
            field=models.ImageField(default='static/health_images/default.jpg', upload_to=news.models.generate_image_filename_01),
        ),
    ]
