# Generated by Django 4.0.4 on 2023-01-02 10:20

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_health_news_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='science_news',
            name='img',
            field=models.ImageField(default='static/science_images/default.jpg', upload_to=news.models.generate_image_filename_04),
        ),
        migrations.AlterField(
            model_name='sport_news',
            name='img',
            field=models.ImageField(default='static/sport_images/default.jpg', upload_to=news.models.generate_image_filename_02),
        ),
        migrations.AlterField(
            model_name='tech_news',
            name='img',
            field=models.ImageField(default='static/tech_images/default.jpg', upload_to=news.models.generate_image_filename_03),
        ),
    ]
